### ISSUE TITLE
Cannot compile with PHP 7.0 & PHP 7.1: phpext_igbinary_ptr error

### ISSUE THREAD

**Issue by HansVanEijsden** [igbinary/igbinary#72]
Thanks for all the efforts. But unfortunately I cannot compile the extension with PHP.
I tried it with PHP 7.0.10 and PHP 7.1.0 beta 3:

```
main/internal_functions_cli.c:115:2: error: 'phpext_igbinary_ptr' undeclared here (not in a function)
  phpext_igbinary_ptr,
  ^
Makefile:2257: recept voor doel 'main/internal_functions_cli.lo' is mislukt
make: *** [main/internal_functions_cli.lo] Fout 1
```

It always hangs on this error.
Using the fork from @TysonAndre https://github.com/TysonAndre/igbinary gives the same error.

When I use https://github.com/igbinary/igbinary7.git all is well. But that one seems to be deprecated, recently. What do do now?

```
uname -a
Linux vps 4.6.0-0.bpo.1-amd64 #1 SMP Debian 4.6.4-1~bpo8+1 (2016-08-11) x86_64 GNU/Linux
```

```
gcc --version
gcc-4.9.real (Debian 4.9.2-10) 4.9.2
```

`./configure --prefix=/opt/php-7.1.0 --with-libdir=/lib/x86_64-linux-gnu --enable-fpm --with-fpm-systemd --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi --with-libxml-dir=/usr --with-openssl --with-kerberos --with-pcre-regex --with-zlib --with-pcre-regex --enable-bcmath --with-bz2 --enable-calendar --with-curl=/usr/local --enable-exif --enable-ftp --with-gd --with-jpeg-dir=/usr --with-png-dir=/usr --with-xpm-dir=/usr --with-freetype-dir --enable-gd-native-ttf --enable-gd-jis-conv --with-gettext --with-mhash --with-imagick --with-imap --with-kerberos --with-imap-ssl --enable-intl --with-ldap --with-ldap-sasl --enable-mbstring --enable-memcached --enable-memcached-json --with-mysqli --enable-pcntl --with-pdo-mysql --with-pspell --enable-shmop --enable-soap --enable-sockets --enable-sysvmsg --enable-sysvsem --enable-sysvshm --with-tidy --with-xmlrpc --with-xsl --enable-zip --enable-wddx --enable-mysqlnd --with-pear --with-iconv --with-gmp --enable-zend-signals --with-mcrypt --disable-rpath --enable-mbregex --enable-re2c-cgoto --enable-redis --enable-igbinary --enable-memcached-igbinary --enable-redis-igbinary CFLAGS="-O3 -march=native" CXXFLAGS="-O3 -march=native"`

**Comment by TysonAndre** [comment]
Are you trying to compile igbinary statically (or as a .so)

What folder is the php source code found in? What folder is the igbinary source code found in?

(If compiling as an so file (shared), igbinary should be outside of the php source code directory.

**Comment by HansVanEijsden** [comment]
Thanks for your quick reply @TysonAndre. I am trying to compile statically as I'm used to.
Here are all the steps I take: http://pastebin.com/fRsHGzPm

The PHP source code is in /usr/local/src/php5-build/php-7.0.10 and the igbinary source code is in /usr/local/src/php5-build/php-7.0.10/ext (so I use ./buildconf --force to regenerate).
Am I doing it wrong?

**Comment by TysonAndre** [comment]
No, it's a bug in the way I moved things into src/php5 and src/php7.

ext/igbinary/php_igbinary.h needs to exist for the extension to be compiled statically, and I wasn't aware of this when making the change. It's easy to patch by copying ext/igbinary/src/php7/php_igbinary.h to ext/igbinary/php_igbinary.h and running buildconf again - Will resume work on this later today

**Comment by HansVanEijsden** [comment]
Thanks again, by moving ext/igbinary/src/php7/php_igbinary.h to ext/igbinary/php_igbinary.h manually, using your fork. And session.serialize_handler as igbinary works too now. 
Keep up the good work!

**Comment by HansVanEijsden** [comment]
Unfortunately, it still doesn't work, the same error (in PHP5 & PHP7). When I manually copy php_igbinary.h all is fine.

**Comment by TysonAndre** [comment]
Odd, it worked for me 3 weeks ago. Maybe gcc is failing to compile ext/igbinary/php_igbinary.h since it can't find ext/igbinary/src/php7/php_igbinary.h in the search path, so the generated main/internal_functions_cli.c doesn't end up including the line "ext/igbinary/php_igbinary.h"

Will try to reproduce with configure args and gcc 4.9 later on.

Try using a fresh php-src checkout? Also, could you put the contents of main/internal_functions_cli.c and ext/php_igbinary.h and the layout of `ext/` (e.g. `ls -laR ext/`) in a gist? main/internal_functions_cli.c should have a line saying "ext/igbinary/php_igbinary.h", unless the compiler failed to process it for your setup somehow.

**Comment by HansVanEijsden** [comment]
Thans for taking the time to reproduce it and I think you're right about the search path: it's missing indeed in main/internal_functions_cli.c.
I cannot use a fresh php-src checkout, because my Bison version is the banned 3.0 (Debian Jessie default). I use the official release tar.gz from the PHP website.

Here is the gist you asked for, trying to build PHP 5.6.26: https://gist.github.com/HansVanEijsden/5aa4b2855715714e50ecaa9c1b3a9d83
