### PR TITLE
Fix build with PHP 8.6: unserialize_callback_func is a zend_string

### LINKED ISSUE #418: Fails to compile with php 8.6.0 beta 1
When compiling with the latest 8.6.0 beta it fails to compile with the following error:

```
/sources/php-8.6.0beta1/ext/igbinary/src/php7/igbinary.c: In function 'igbinary_unserialize_object':
/sources/php-8.6.0beta1/ext/igbinary/src/php7/igbinary.c:3182:32: error: assignment to 'const char *' from incompatible pointer type 'zend_string *' {aka 'struct _zend_string *'} [-Wincompatible-pointer-types]
 3182 |                 user_func_name = PG(unserialize_callback_func);
      |                                ^
/sources/php-8.6.0beta1/ext/igbinary/src/php7/igbinary.c:3213:70: warning: format '%s' expects argument of type 'char *', but argument 4 has type 'zend_string *' {aka 'struct _zend_string *'} [-Wformat=]
 3213 |                         php_error_docref(NULL, E_WARNING, "Function %s() hasn't defined the class it was called for", PG(unserialize_callback_func));
      |                                                                     ~^
      |                                                                      |
      |                                                                      char *
make: *** [Makefile:1035: ext/igbinary/src/php7/igbinary.lo] Error 1
````

I haven't had time to dig into the error yet.

### PR DESCRIPTION
**Pull request by andypost**
php-src https://github.com/php/php-src/commit/c82acefe470 (php 8.6.0beta1) converted the PG(unserialize_callback_func) global from char* to zend_string*.

Fixes #418

### CODE REVIEW

**Review by remicollet — APPROVED** [review]
LGTM, tested with 8.6.0beta1

**Comment by wyattoday** [comment]
Tested and works for us. Thanks @andypost !

@tricky , any chance you could review and merge so other people can get the fixes too?

**Comment by michael-grunder** [comment]
Is there anything blocking this from being merged?
