### ISSUE TITLE
Fails to compile with php 8.6.0 beta 1

### ISSUE THREAD

**Issue by wyattoday** [igbinary/igbinary#418]
When compiling with the latest 8.6.0 beta it fails to compile with the following error:

```
/sources/php-8.6.0beta1/ext/igbinary/src/php7/igbinary.c: In function 'igbinary_unserialize_object':
/sources/php-8.6.0beta1/ext/igbinary/src/php7/igbinary.c:3182:32: error: assignment to 'const char *' from incompatible pointer type 'zend_string *' {aka 'struct _zend_string *'} [-Wincompatible-pointer-types]
 3182 |                 user_func_name = PG(unserialize_callback_func);
      |                                ^
/sources/php-8.6.0beta1/ext/igbinary/src/php7/igbinary.c:3213:70: warning: format '%s' expects argument of type 'char *', but argument 4 has type 'zend_string *' {aka 'struct _zend_string *'} [-Wformat=]
 3213 |                         php_error_docref(NULL, E_WARNING, "Function %s() hasn't defined the class it was called for", PG(unserialize_callback_func));
      |                                                                     ~^
      |                                                                      |
      |                                                                      char *
make: *** [Makefile:1035: ext/igbinary/src/php7/igbinary.lo] Error 1
````

I haven't had time to dig into the error yet.

**Comment by andypost** [comment]
confirm it, caused by https://github.com/php/php-src/commit/c82acefe470
